### ISSUE TITLE
Unhandled exception when closing connection due to timeout

### ISSUE THREAD

**Issue by milosivanovic** [milosivanovic/xbot#1]
```
Traceback (most recent call last):
  File "/usr/local/bin/irc_beta/bot", line 15, in <module>
    bot.run()
  File "/usr/local/bin/irc_beta/xbot/__init__.py", line 18, in run
    self.bot.connect(self.hosts[i][0], int(self.hosts[i][1]))
  File "/usr/local/bin/irc_beta/xbot/irc.py", line 57, in connect
    self._loop()
  File "/usr/local/bin/irc_beta/xbot/irc.py", line 62, in _loop
    self._select()
  File "/usr/local/bin/irc_beta/xbot/irc.py", line 98, in _select
    self._recv(sock, 1500)
  File "/usr/local/bin/irc_beta/xbot/irc.py", line 141, in _recv
    self._log("dbg", "Closed connection from %s:%d" % (self.sockets.inputs[sock][0], self.sockets.inputs[sock][1]))
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by milosivanovic** [comment]
Fixed by d84fc3dc.
